import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Keep Inter import as it's used in ClientLayout

import ClientLayout from "./layout-client"; // Import the client layout

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
});

// Original metadata export
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientLayout>{children}</ClientLayout>
  );
}